import type { Metadata } from "next";
import { SITE } from "@/lib/site";

export const SEO = {
  title: "Shiver Broker | Corretora Forex, Crypto e Opções",
  titleHome: "Shiver Broker | Corretora dos Grandes Tubarões — Forex, Crypto e Opções",
  description: SITE.description,
  keywords: [
    "Shiver",
    "Shiver Broker",
    "ShiverBroker",
    "shiverbroker",
    "corretora Shiver",
    "Shiver corretora",
    "Shiver investir",
    "Shiver investimento",
    "Shiver login",
    "Shiver Broker login",
    "conta demo Shiver",
    "plataforma Shiver",
    "forex Shiver",
    "crypto Shiver",
    "opções binárias Shiver",
    "corretora forex",
    "corretora crypto",
    "payout 97%",
  ],
  ogImage: {
    url: "/og.png",
    width: 1200,
    height: 630,
    alt: "Shiver Broker — A Corretora dos Grandes Tubarões",
  },
} as const;

export function siteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${SITE.url}/#organization`,
        name: "Shiver Broker",
        legalName: "Sun Wave LLC",
        alternateName: ["Shiver", "ShiverBroker", "Corretora Shiver", "Shiver Broker corretora"],
        url: SITE.url,
        email: SITE.email,
        logo: {
          "@type": "ImageObject",
          url: `${SITE.url}/icon.png`,
          width: 512,
          height: 512,
        },
        image: `${SITE.url}/og.png`,
        slogan: SITE.tagline,
        foundingLocation: {
          "@type": "Place",
          name: "Charlestown, Nevis",
        },
        sameAs: ["https://trade.shiverbroker.com", SITE.url],
        contactPoint: {
          "@type": "ContactPoint",
          email: SITE.email,
          contactType: "customer support",
          availableLanguage: ["Portuguese", "English"],
        },
      },
      {
        "@type": "Brand",
        "@id": `${SITE.url}/#brand`,
        name: "Shiver",
        alternateName: ["Shiver Broker", "ShiverBroker"],
        url: SITE.url,
        logo: `${SITE.url}/icon.png`,
      },
      {
        "@type": "WebSite",
        "@id": `${SITE.url}/#website`,
        url: SITE.url,
        name: "Shiver Broker",
        alternateName: ["Shiver", "ShiverBroker.com"],
        description: SITE.description,
        inLanguage: "pt-BR",
        publisher: { "@id": `${SITE.url}/#organization` },
        about: { "@id": `${SITE.url}/#brand` },
      },
      {
        "@type": "WebPage",
        "@id": `${SITE.url}/#webpage`,
        url: SITE.url,
        name: SEO.titleHome,
        description: SITE.description,
        inLanguage: "pt-BR",
        isPartOf: { "@id": `${SITE.url}/#website` },
        about: { "@id": `${SITE.url}/#organization` },
        primaryImageOfPage: {
          "@type": "ImageObject",
          url: `${SITE.url}/og.png`,
        },
      },
      {
        "@type": "FinancialService",
        "@id": `${SITE.url}/#service`,
        name: "Shiver Broker",
        alternateName: "Shiver",
        description: SITE.description,
        url: SITE.url,
        image: `${SITE.url}/og.png`,
        areaServed: "Worldwide",
        availableLanguage: ["pt-BR", "en"],
        brand: { "@id": `${SITE.url}/#brand` },
        provider: { "@id": `${SITE.url}/#organization` },
        parentOrganization: { "@id": `${SITE.url}/#organization` },
        serviceType: ["Forex", "Cryptocurrency trading", "Binary options"],
        offers: {
          "@type": "Offer",
          name: "Conta demo Shiver Broker",
          description: "Teste a plataforma Shiver com $10.000 virtuais, sem depósito.",
          url: SITE.trade.trial,
          price: "0",
          priceCurrency: "USD",
        },
      },
    ],
  };
}

export const defaultMetadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SEO.title,
    template: "%s | Shiver Broker",
  },
  description: SITE.description,
  applicationName: "Shiver Broker",
  generator: "Shiver Broker",
  referrer: "origin-when-cross-origin",
  category: "finance",
  keywords: [...SEO.keywords],
  authors: [{ name: "Shiver Broker", url: SITE.url }],
  creator: "Shiver Broker",
  publisher: "Sun Wave LLC",
  formatDetection: { telephone: false, email: false, address: false },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: SITE.url,
    siteName: "Shiver Broker",
    title: SEO.titleHome,
    description: SITE.description,
    images: [SEO.ogImage],
  },
  twitter: {
    card: "summary_large_image",
    title: SEO.titleHome,
    description: SITE.description,
    images: [SEO.ogImage.url],
  },
  alternates: {
    languages: {
      "pt-BR": SITE.url,
      "x-default": SITE.url,
    },
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: { icon: "/icon.png", apple: "/icon.png", shortcut: "/icon.png" },
  manifest: "/manifest.webmanifest",
};
